# fly.toml app configuration file generated for ali-al-baker-api on 2026-07-01T08:33:38Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ali-al-baker-api'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile.api'

[env]
  SERVE_AUTH_UI = 'false'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '45s'
    method = 'GET'
    path = '/api/health'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
